### ISSUE TITLE
AAAR View renders as text/plain instead of HTML

### ISSUE THREAD

**Issue by synatree** [fcorti/alfresco-audit-analysis-reporting#13] opened 2015-02-16 18:58 UTC
After following installation instructions, I get the following view:

![image](https://cloud.githubusercontent.com/assets/7294077/6217517/da55af56-b5e2-11e4-9b8e-4782fcf3389c.png)

Marketplace Versions:

![image](https://cloud.githubusercontent.com/assets/7294077/6217555/285b0d2c-b5e3-11e4-9a41-81030f5c90b4.png)

I've upgraded Sparkl and downgraded Saiku to see if I could resolve the issue, but nothing has helped.

**Comment by fcorti** [comment] 2015-02-16 19:02
Hi,
Please share details about the environment:
Which Pentaho version?
Which Linux platform?
Which AAAR version?
No GUI, right?

**Comment by synatree** [comment] 2015-02-16 19:39
Pentaho 5.2.0.0.209

Gentoo Linux 3.6.11-gentoo x86_64 Intel(R) Xeon(R) CPU E5620 @ 2.40GHz
GenuineIntel GNU/Linux

AAAR version 2.3 Stable according to screenshot

I did get a GUI set up, and ran Spoon.  Spoon opened successfully; I just
closed it afterwards.

**Comment by synatree** [comment] 2015-02-16 19:47
Possibly relevant:  I'm running Pentaho under Apache Mod_JK on an alternate port.  Here's my server.xml:
```xml
<!-- A "Connector" represents an endpoint by which requests are received
         and responses are returned. Documentation at :
         Java HTTP Connector: /docs/config/http.html (blocking & non-blocking)
         Java AJP  Connector: /docs/config/ajp.html
         APR (HTTP/AJP) Connector: /docs/apr.html
         Define a non-SSL HTTP/1.1 Connector on port 8080
    -->
    <Connector URIEncoding="UTF-8" port="7080" protocol="HTTP/1.1"
               connectionTimeout="20000"
               redirectPort="7443" />
    <!-- A "Connector" using the shared thread pool-->
    <!--
    <Connector URIEncoding="UTF-8" executor="tomcatThreadPool"
               port="7080" protocol="HTTP/1.1"
               connectionTimeout="20000"
               redirectPort="7443" />
    -->
    <!-- Define a SSL HTTP/1.1 Connector on port 8443
         This connector uses the JSSE configuration, when using APR, the
         connector should be using the OpenSSL style configuration
         described in the APR documentation -->
    <!--
    <Connector URIEncoding="UTF-8" port="7443" protocol="HTTP/1.1" SSLEnabled="true"
               maxThreads="150" scheme="https" secure="true"
               clientAuth="false" sslProtocol="TLS" />
    -->

    <!-- Define an AJP 1.3 Connector on port 8009 -->
    <Connector URIEncoding="UTF-8" port="7009" protocol="AJP/1.3" redirectPort="7443" />
```

And here's my tomcat/webapps/pentaho/web.xml:

```xml

<!--  This context parameter is being deprecated. We don't use this any more. We have added a new context parameter called fully-qualified-server-url -->
  <context-param>
    <param-name>base-url</param-name>
    <param-value>http://servername/pentaho/</param-value>
  </context-param>

  <!--  FullyQualifiedServerUrl is used only in the case of offline content generation and whenever something need to talk back to the server -->
  <context-param>
    <param-name>fully-qualified-server-url</param-name>
    <param-value>http://servername/pentaho/</param-value>
  </context-param>
```

**Comment by fcorti** [comment] 2015-02-16 20:35
The problem could be the apache settings but I suspect the problem is in the CDF, CDE, CDA addon.
Please check the correct installation of the same version (the 5.2.xxx) of the quoted CTools addons.
What you see into the panel is exactly the HTML generated from Pentaho and seems to be that Pentaho cannot recognize the resulting HTML as HTML mimetype, but generate the result as text mimetype.

**Comment by synatree** [comment] 2015-02-16 20:58
All up to date....

![image](https://cloud.githubusercontent.com/assets/7294077/6219212/985c89e6-b5f4-11e4-8b54-290fd48b9535.png)

**Comment by fcorti** [comment] 2015-02-16 21:04
Ok!
Please, create a brand new CDE dashboard using the Pentaho User Console, more in detail: File => New => CDE Dashboard.
Once you have the empty dashboard, please, create a Row and a HTML element with the content described below.
![schermata 2015-02-16 alle 22 01 11](https://cloud.githubusercontent.com/assets/6010860/6219259/72e39eba-b627-11e4-8a77-f2c9f5a18bb1.png)

Save the dashboard  in the public folder of the repository.
Finally, open the dashboard using the browse item of the menu.

This test is useful to understand if the problem is the CTools (as I suppose).
If you see the same "bad result" => the problem is in the CTools.

**Comment by fcorti** [comment] 2015-02-16 21:35
A similar issue in the past...
http://redmine.webdetails.org/issues/3231
But I always use the Pentaho 5.2 + AAAR v2.3

**Comment by synatree** [comment] 2015-02-16 21:48
The approach you suggested yielded a correct HTML rendering...

![image](https://cloud.githubusercontent.com/assets/7294077/6219727/73db19a0-b5fb-11e4-8974-cb3236a25092.png)

**Comment by synatree** [comment] 2015-02-16 21:55
The kicker is, if I copy and paste the AAAR html into helloworld, it actually does work (clicking links results in those pages rendering as text/plain).

I've also downgraded to AAAR 2.2 with no effect, suggesting it is some kind of issue with CTools.  It must be subtle whatever it is.

**Comment by fcorti** [comment] 2015-02-16 22:11
Please, edit the dashboard and save it again without modifications.
During the saving you will probably get a message similar to "some tags could be ignored or replaced".
Don't mind about that... is what I would like to test.
After saving, please reopen the dashboard sharing the result.

This test is to check if the dashboards contain some tags the Pentaho 5.2 does not accept.

Another test could be on the encoding.
Which encoding/language do you use into your environment?

**Comment by synatree** [comment] 2015-02-16 22:14
I'll do all of that and get back to you; in the meantime I'm wondering - is /pentaho the only webapp that is used?  I see in the tomcat/webapps directory pentaho-style and sw-style, which I don't have mapped through mod_jk.  Could this be the issue?

**Comment by fcorti** [comment] 2015-02-16 22:19
For sure not directly but I don't if requested from pentaho.
You could try to include.
Otherwise... could try a more standard installation.

**Comment by synatree** [comment] 2015-02-16 22:55
OK - I have a solution.  I think there is a problem with the design of the javascript code.  First, the solution:

Always use the port number that Tomcat is running on.  Don't pass AAAR through a proxy.  As soon as I targeted port 8080 (7080 for me), AAAR came up.

I think this is happening because javascripts cannot access data across different domains; in this case http://myserver/pentaho and http://myserver:7080/pentaho are technically different servers.  I am not sure where a port number is being used in your code (or in CDE), but it should really respect the settings in tomcat/webapps/pentaho/WEB-INF/web.xml and tomcat/config/server.xml.  At any rate, the result is broken AAAR.

Thanks for your help with this Francesco.  I'll work around the problem until a solution is found.  I'm pretty sure you'll be able to reproduce if you pass Pentaho through mod_jk or even apache mod_proxy.

Here's my config to save you some time:

apache vhost.conf
```
...
#unmount Pentaho resources from Alfresco Worker
JkUnMount /pentaho/* alfresco
JkUnmount /pentaho-style/* alfresco
JkUnMount /sw-style/* alfresco

#mount Pentaho resources to Pentaho worker...
JkMount /pentaho/* pentaho
JkMount /pentaho-style/* pentaho
JkMount /sw-style/* pentaho
```
jk-worker.properties
```sh
worker.list=pentaho
worker.pentaho.reference=worker.template
worker.pentaho.host=localhost
worker.pentaho.port=7009
worker.pentaho.activation=A
# Finally we put the parameters
# which should apply to all our ajp13
# workers into the referenced template
# - Type is ajp13
worker.template.type=ajp13

# - socket_connect_timeout: milliseconds, default=0
#   Since: 1.2.27
worker.template.socket_connect_timeout=5000

# - socket_keepalive: boolean, default=false
#   Should we send TCP keepalive packets
#   when connection is idle (socket option)?
worker.template.socket_keepalive=true

# - ping_mode: Character, default=none
#   When should we use cping/cpong connection probing?
#   C = directly after establishing a new connection
#   P = directly before sending each request
#   I = in regular intervals for idle connections
#       using the watchdog thread
#   A = all of the above
#   Since: 1.2.27
worker.template.ping_mode=A

# - ping_timeout: milliseconds, default=10000
#   Wait timeout for cpong after cping
#   Can be overwritten for modes C and P
#   Using connect_timeout and prepost_timeout.
#   Since: 1.2.27
worker.template.ping_timeout=10000

# - connection_pool_minsize: number, default=connection_pool_size
#   Lower pool size when shrinking pool due
#   to idle connections
#   We want all connections to be closed when
#   idle for a long time in order to prevent
#   firewall problems.
#   Since: 1.2.16
worker.template.connection_pool_minsize=0

# - connection_pool_timeout: seconds, default=0
#   Idle time, before a connection is eligible
#   for being closed (pool shrinking).
#   This should be the same value as connectionTimeout
#   in the Tomcat AJP connector, but there it is
#   milliseconds, here seconds.
worker.template.connection_pool_timeout=600

# - reply_timeout: milliseconds, default=0
#   Any pause longer than this timeout during waiting
#   for a part of the reply will abort handling the request
#   in mod_jk. The request will proceed running in
#   Tomcat, but the web server resources will be freed
#   and an error is send to the client.
#   For individual requests, the timeout can be overwritten
#   by the Apache environment variable JK_REPLY_TIMEOUT.
#   JK_REPLY_TIMEOUT since: 1.2.27
worker.template.reply_timeout=300000

# - recovery_options: number, default=0
#   Bit mask to configure, if a request, which was send
#   to a backend successfully, should be retried on another backend
#   in case there's a problem with the response.
#   Value "3" disables retries, whenever a part of the request was
#   successfully send to the backend.
worker.template.recovery_options=3
```

**Comment by fcorti** [comment] 2015-02-17 06:57
Good job!
I close this issue to open a new one more detailed on that.

**Closed by fcorti** 2015-02-17 06:57 UTC
Labels: help wanted
