### ISSUE TITLE
Pentaho Business Analytics Platform - Installation issue

### ISSUE THREAD

**Issue by Manirangasamy** [fcorti/alfresco-audit-analysis-reporting#50] opened 2017-04-28 01:51 UTC
Hi,

I am following the A.A.A.R. – Prerequisites.  I installed the "Pentaho Data Integration" and launched the spoon. 
Now, I have download the pentaho-server-ce-7.0.0.0-25.zip and extracted. executed the pentaho.sh and got below output. When type http://<servername>:8080/pentaho and it is not loading 
The requested URL /pentaho was not found on this server. http://<servername>:8080/ is working

Below is the environment  and I have installed the mysql. By looking at log and catalina.out, I understand that it is by default using the HSQLDB server 2.3.2 is online on port 9001.  I copied the error, is the because of port is not opened or something else. Is there way to change the database to mysql instead of HSQLDB

Server version:        Apache Tomcat/8.0.37
Server built:          Sep 1 2016 10:01:52 UTC
Server number:         8.0.37.0
OS Name:               Linux
OS Version:            2.6.39-400.286.3.el5uek
Architecture:          amd64
Java Home:             /usr/java/jdk1.8.0_131/jre
JVM Version:           1.8.0_131-b11
JVM Vendor:            Oracle Corporation
CATALINA_BASE:         /oracle/app/pentaho/pentaho-server/tomcat
CATALINA_HOME:         /oracle/app/pentaho/pentaho-server/tomcat

And I  am getting below error in catalina.out

27-Apr-2017 17:14:25.165 SEVERE [main] org.apache.coyote.AbstractProtocol.init Failed to initialize end point associated with ProtocolHandler ["http-nio-8080"]
 java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)

27-Apr-2017 17:14:25.167 SEVERE [main] org.apache.catalina.core.StandardService.initInternal Failed to initialize connector [Connector[HTTP/1.1-8080]]
 org.apache.catalina.LifecycleException: Failed to initialize component [Connector[HTTP/1.1-8080]]
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
17:15:18,473 ERROR [HsqlDatabaseStarterBean] HsqlDatabaseStarterBean.ERROR_0006 - The default port of 9001 is already in use. Do you already have HSQLDB running in another process? The HSQLDB Starter cannot continue.
17:15:19,171 INFO  [PeriodicStatusLogger] Caution, the system is initializing. Do not shut down or restart the system at this time.
17:15:20,574 WARN  [PentahoSolutionSpringApplicationContext] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.h2.tools.Server' defined in file [/oracle/app/pentaho/pentaho-server/pentaho-solutions/system/GettingStartedDB-spring.xml]: Invocation of init method failed; nested exception is org.h2.jdbc.JdbcSQLException: Exception opening port "9092" (port may be in use), cause: "java.net.BindException: Address already in use (Bind failed)" [90061-131]
17:15:20,593 ERROR [ContextLoader] Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.h2.tools.Server' defined in file [/oracle/app/pentaho/pentaho-server/pentaho-solutions/system/GettingStartedDB-spring.xml]: Invocation of init method failed; nested exception is org.h2.jdbc.JdbcSQLException: Exception opening port "9092" (port may be in use), cause: "java.net.BindException: Address already in use (Bind failed)" [90061-131]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
Caused by: org.h2.jdbc.JdbcSQLException: Exception opening port "9092" (port may be in use), cause: "java.net.BindException: Address already in use (Bind failed)" [90061-131]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:316)
	at org.h2.message.DbException.get(DbException.java:156)

**Comment by fcorti** [comment] 2017-05-01 13:57
Hi Manirangasamy,

The problem is in the installation of the BA server.
Pentaho BA server should be available at http://localhost:8080/pentaho.
I'm not sure http://:8080 is a valid URL.

The error message says: Address already in use.
You probably have a conflict and something else already running on port 8080.

I hope this help.

Considering this is not a bug, if you need more support, please move the discussion on the https://community.alfresco.com/ portal where I can help you.
I'm going to close this issue here.

Cheers.

**Closed as completed by fcorti** 2017-05-01 13:57 UTC
